---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: microsoft
name: scom
version: 0.1.0
readme: README.md
authors:
  - Hen Yaish (github.com/yaish25491)
  - Shahar Golshani (github.com/shahargolshani)
  - Mike Morency (github.com/mikemorency)
description: Ansible collection for Microsoft System Center Operations Manager (SCOM) automation
license_file: LICENSE
tags:
  - microsoft
  - scom
  - monitoring
  - operations
  - windows
  - infrastructure
repository: https://github.com/ansible-collections/microsoft.scom
documentation: https://github.com/ansible-collections/microsoft.scom/tree/main/docs
homepage: https://github.com/ansible-collections/microsoft.scom
issues: https://github.com/ansible-collections/microsoft.scom/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
