---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: microsoft
name: scom
version: 1.0.1
readme: README.md
authors:
  - Microsoft SCOM Collection Contributors (@ansible-collections)
description: Ansible Collection for interacting with Microsoft System Center Operations Manager
license_file: LICENSE
tags:
  - eda
  - scom
  - monitoring
  - microsoft
repository: https://github.com/ansible-collections/microsoft.scom
homepage: https://github.com/ansible-collections/microsoft.scom
issues: https://github.com/ansible-collections/microsoft.scom/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
