- name: Prepare release
  hosts: localhost
  vars:
    testrun: false
  tasks:
    - name: Generate next release version
      when: version is not defined
      block:
        - name: Get the next release version
          ansible.builtin.shell: >-
            set -o pipefail &&
            git tag --sort=-creatordate --merged |
            head -n1 |
            perl -pe 's/(\d+\.)(\d+)\.\d+/"$1" . ($2+1) . ".0"/e'
          args:
            executable: /bin/bash
          register: result
          changed_when: false

        - name: Set the release version
          ansible.builtin.set_fact:
            version: "{{ result.stdout }}"

    - name: Install antsibull-docs and antsibull-changelog
      ansible.builtin.pip:
        name:
          - antsibull-docs
          - antsibull-changelog

    - name: Create release branch
      ansible.builtin.command: git checkout -b "prepare_{{ version }}_release"  # noqa: command-instead-of-module
      when: not testrun
      changed_when: true

    - name: Update release files and commit changes
      block:
        - name: Update galaxy.yml
          ansible.builtin.lineinfile:
            path: "{{ playbook_dir }}/../galaxy.yml"
            regexp: "^version: "
            line: "version: {{ version }}"

        - name: Update documentation
          ansible.builtin.command: >-
            antsibull-docs collection-plugins microsoft.scom
            --dest-dir {{ playbook_dir }}/../docs
            --use-current
            --output-format simplified-rst
            --fqcn-plugin-names
          changed_when: true

        - name: Refresh the changelog
          ansible.builtin.command: 'antsibull-changelog release --verbose --version {{ version }}'
          changed_when: true

        - name: Find the yaml file
          ansible.builtin.find:
            paths: "{{ playbook_dir }}/../changelogs/fragments"
            excludes: ".gitkeep,"
          register: files_to_delete
          when: not testrun

        - name: Clean up the changelog fragments
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ files_to_delete.files }}"
          when: not testrun

        - name: Check correct version in docs
          ansible.builtin.command: "grep -r 'version {{ version }}' {{ playbook_dir }}/../docs"
          register: version_check
          changed_when: false

        - name: Add everything
          ansible.builtin.command: git add --all  # noqa: command-instead-of-module
          when: not testrun
          changed_when: true

          # git diff-index --quiet HEAD
          #   0 -> repository is clean, nothing to commit
          #   1 -> the opposite
        - name: Commit everything
          ansible.builtin.shell: 'git diff-index --quiet HEAD || git commit -m "prepare {{ version }} release"'  # noqa: command-instead-of-module
          when: not testrun
          changed_when: true

      rescue:
        - name: Display failure message
          ansible.builtin.debug:
            msg: "Failed to release {{ version }}. Git source is dirty, perform 'git branch -D prepare_{{ version }}_release' before running this playbook."
